apiVersion: v1
kind: Service

metadata:
  name: {{ include "fastapi-chart.fullname" . }}

spec:
  type: {{ .Values.service.type }}

  selector:
    app: {{ include "fastapi-chart.name" . }}

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}