services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
      - redis
    environment:
      DB_HOST: postgres-db
      DB_USER: postgres
      DB_PASSWORD: pass
      DB_NAME: postgres
      REDIS_HOST: redis

  postgres-db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:8
    restart: unless-stopped

volumes:
  postgres-data: