FROM python:3.14-slim

WORKDIR /app

COPY app/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Create a dedicated user
RUN useradd --create-home appuser

# Switch to that user
USER appuser

COPY --chown=appuser:appuser app/ .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]