# ------------------------
# Stage 1 - Builder
# ------------------------
FROM python:3.14 AS builder

WORKDIR /install

COPY app/requirements.txt .

RUN pip install \
    --no-cache-dir \
    --prefix=/install \
    -r requirements.txt

# ------------------------
# Stage 2 - Runtime
# ------------------------
FROM python:3.14-slim

WORKDIR /app

COPY --from=builder /install /usr/local

COPY app/ .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]